# Compose V2 (no version key needed)

networks:
  backend: {}

volumes:
  var: {}
  vendor: {}
  node_modules: {}
  db-data: {}

services:
  # === EC-CUBE (PHP 8.1 + Apache) ===
  ec-cube:
    platform: "linux/amd64"          # Apple Silicon fix
    image: ${REGISTRY:-ghcr.io}/${IMAGE_NAME:-ec-cube/ec-cube-php}:${TAG:-8.1-apache}
    ports:
      - "8080:80"                    # change left port if 8080 is taken (e.g., 8085:80)
      - "4430:443"
    volumes:
      - "var:/var/www/html/var"
      - "vendor:/var/www/html/vendor"
      - "node_modules:/var/www/html/node_modules"
    environment:
      APP_ENV: "dev"
      APP_DEBUG: 1
      # Use root so EC-CUBE can create/use the DB cleanly
      DATABASE_URL: "mysql://root:root@db:3306/eccube"
      DATABASE_SERVER_VERSION: 8.0
      DATABASE_CHARSET: "utf8mb4"
      MAILER_DSN: "smtp://mailcatcher:1025"
      ECCUBE_AUTH_MAGIC: "<change.me>"
    depends_on:
      - db
      - mailcatcher
    networks:
      - backend

  # === MySQL 8 ===
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      # (intentionally NOT setting MYSQL_DATABASE/USER/PASSWORD to avoid conflicts)
    ports:
      - "3306:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - backend

  # === phpMyAdmin ===
  phpmyadmin:
    platform: "linux/amd64"          # Apple Silicon fix
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - backend

  # === Mailcatcher (dev mail) ===
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - backend
